name: Generate coverage badge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: report coverage
        run: |
          coverage run
          coverage xml
      - name: generate badge
        run: genbadge coverage -i - < coverage.xml
