# name: Generate coverage badge

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Install dependencies
#         run: | 
#           python -m pip install --upgrade pip
#           pip install coverage
#           pip install genbadge[all]
#       - name: Report cov
#         run: |
#           coverage run -m unittest discover
#           coverage report -m
#           coverage xml
#       - name: generate badge
#         run: genbadge coverage -i - < coverage.xml
